### ISSUE TITLE
It is stuck after "Overwrote ./bedrock-server-1.17.41.01/server.properties based on contents of ./config.json"

### ISSUE THREAD

**Issue by zisen123** [debkbanerji/minecraft-bedrock-server#4] opened 2021-11-29 22:18 UTC
Hello developers, thanks for your application, but when I want to run my server it was stuck after I typed "npm start".
```shell
senux@MiLaptop:~/Ziserver$ npm start

> minecraft-bedrock-node@2021.11.11 start /home/senux/Ziserver
> node main.js

!!!!!!!!!!
config["backup"]["use-aws-s3-backup"] set to false - if you want to use AWS S3 backups, set this to true and see https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html for instruction on how to define your AWS credentials
!!!!!!!!!!

Starting express server
Running UI for server on port 3000

Minecraft server (./bedrock-server-1.17.41.01) already exists - no need to redownload
./bedrock-server-1.17.41.01/server.properties
Overwrote ./bedrock-server-1.17.41.01/server.properties based on contents of ./config.json
```
And here is the ui webpage shows:
```
Minecraft Bedrock Server
Server source code and documentation: github.com/debkbanerji/minecraft-bedrock-server
Refresh frequency: every 
5 Seconds (recommended)
Server Resource Usage Info:
Error connecting to server
Server Terminal Output:
20 latest lines of terminal output:
Starting express server
Running UI for server on port 3000

Minecraft server (./bedrock-server-1.17.41.01) already exists - no need to redownload
./bedrock-server-1.17.41.01/server.properties
Overwrote ./bedrock-server-1.17.41.01/server.properties based on contents of ./config.json
```
here is some specifics you may need
```
Ubuntu-20.04 on Windows 10 Pro 21H2 OS build 19044.1348
nodejs v14.18.1
npm 6.14.15
```

**Comment by debkbanerji** [comment] 2021-11-30 04:04
Can you share a copy of your config file so I can debug this?

**Comment by zisen123** [comment] 2021-11-30 16:42
[config.zip](https://github.com/debkbanerji/minecraft-bedrock-server/files/7627294/config.zip)

**Comment by debkbanerji** [comment] 2021-12-01 03:02
Thanks - looks like the issue is caused by a bug in the lock file code. It should be fixed in the latest version so try pulling the newest version of the code and try again. Sorry for the inconvenience!

I'm closing the issue for now - feel free to reopen if this isn't resolved.

**Closed as completed by debkbanerji** 2021-12-01 03:02 UTC
